# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0f5520ed450cc492a80458c756f7a0bb1ec1c0327bed8d7a700e60ac8a584987dd991cccb8a3d9f564668f4f125cfafa5365aa53539280bfa6ef4b3c1c701fb

test:
  secret_key_base: c4e5d5273ea2b128c01b5d87970b71c2be1fb15b89420b239a340e9f36770bbdecb8f889bdb613a9b73cc02e2b034feffb62bdb72eb73274f88383edea34ec5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
